spring:
  application:
    name: "EngTeacher"
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.7
  mongodb:
    uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@${MONGO_URL}/${MONGO_DATABASE}?authSource=admin
  threads:
    virtual:
      enabled: true